version: "3.8"
  services:
    frontend:

    backend:
      image: node:latest

    database:
      image: mysql
      ports:
        - "8080:80"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123qwe.